on:
  push:
    tags:
      - 'v*'
      - '!v*-voyager'

name: Create Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}
          echo ::set-output name=semver::$semver
        env:
          TAG: ${{ github.ref }}

      - name: Fill Version
        run: |
          tag=${{ steps.semver_parser.outputs.semver }}
          sed -i "s/\$tag_version/$tag/" pom.xml

      - name: Build
        run: mvn clean install
      - name: Prepare Assets
        run: |
          mkdir maven-miner
          mkdir maven-miner/results
          cp README.md maven-miner/README.md
          cp target/mami.jar maven-miner/mami.jar
          cp bin/mami.sh maven-miner/mami.sh
          cp bin/mami.bat maven-miner/mami.bat
      - name: Create Archive
        run: zip -r maven-miner.zip maven-miner

      - name: Prepare Release Notes
        run: touch ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Maven Miner ${{ steps.semver_parser.outputs.semver }}
          body_path: ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md
          body: ""
          prerelease: false
          draft: false
          fail_on_unmatched_files: true
          files: maven-miner.zip
